version: '4'

services:
  postgres:
    image: postgres:17.0-bookworm
    container_name: local_pgdb
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_ADMIN_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/pgsql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@bg.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  postgres-data:
  pgadmin-data: